/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  interface Window {
    sqlbot_assistant_handler?: {
      [key: string]: {
        destroy: () => void
        refresh: (online: boolean, userFlag: number | string) => void
      }
    },
    sqlbot_embedded_handler?: {
      mounted: (selector: string, config: any) => void;
      refresh: (online: boolean, userFlag: number | string) => void;
      destroy: (id: string, deep?: boolean) => void
    };
  }
  
}
