version: '3.8'

services:
  app:
    image: dataease/sqlbot-embedded-demo:dev
    container_name: sqlbot-embedded-demo
    ports:
      - "3000:3000"
    env_file:
      - .env
      # 在docker-compose.yml同级目录下指定.env文件覆盖容器内默认配置
    restart: unless-stopped
    # volumes:
    #   - ./:/usr/src/app